---
- hosts: 127.0.0.1
  remote_user: root
  roles:
    - { role: setup_system, tags: ['system_setup']  }

- hosts: 127.0.0.1
  user: {{ default_user }}
  roles:
    - { role: user_configs, tags: [ 'user_config' ]}
