---
- hosts: 127.0.0.1
  user: root
  sudo: True
  roles:
    - { role: leonidas.nvm, user: stanleyk }

#  tasks:
#    - include: tasks/precise.yml
#      when: ansible_distribution_release  == 'precise'
#    - include: tasks/trusty.yml
#      when: ansible_distribution_release  == 'trusty'
#  handlers:
#    - include: handlers/main.yml
