---
- hosts: 127.0.0.1
  connection: local
  user: skamithi
  sudo: yes
  vars:
    is_s431: "'$ansible_product_version' == 'ThinkPad S3-S431'"
  tasks:
  - name: install unity lenses ppa
    apt_repository: repo="ppa:scopes-packagers/ppa" update_cache=yes
  - name: install ubuntu on rails ppa
    apt_repository: repo="ppa:ubuntu-on-rails/ppa" update_cache=yes
  - name: install  virtualbox repo
    apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian $ansible_distribution_release contrib" update_cache=yes
  - name: install virtualbox apt key
    apt_key: url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc  state=present
  - name: install virtualbox
    apt: pkg=virtualbox-4.2 force=yes
  - name: add Canon printer PPA
    apt_repository: repo='ppa:michael-gruz/canon-stable'
  - name: add TLP repo
    apt_repository: repo='ppa:linrunner/tlp' update_cache=yes
  - name: add partner repo
    apt_repository: repo="deb http://archive.canonical.com/ precise partner" update_cache=yes
  - name: install TLP
    apt: pkg=tlp
  - name: install canon mp560 software
    apt: pkg=$item
    with_items:
      - cnijfilter-mp560series-32
      - scangearmp-mp560series-32
  - name: install pkgs necessary for my system
    apt: pkg=$item
    with_items:
      - gitg
      - skype
      - iotop
      - dialog
      - rcconf
      - transmission
      - build-essential
      - libsnmp-dev
      - libxml2-dev
      - libevent-dev
      - libreadline-dev
      - libsensors4-dev
      - libbsd-dev
      - pkg-config
      - autotools-dev
      - cdbs
      - libgcrypt11-dev
      - debhelper
      - python-software-properties
      - network-manager-vpnc-gnome
      - compizconfig-settings-manager
      - unity-scope-calculator
      - unity-lens-pidgin
      - ack-grep
      - exuberant-ctags
      - gedit-gmate
      - tomboy
      - pidgin
      - libmysqlclient-dev
      - build-essential
      - git-core
      - postgresql
      - revelation
      - dia
      - gip
      - inkscape
      - gimp
      - openssh-server
      - curl
      - vim
      - packaging-dev
      # Required for ADB Chrome Extension
      - libncurses5:i386
  - name: copy zsh deb to /tmp directory
    copy: src=files/zsh_5.0.0-2ubuntu1_amd64.deb dest=/tmp
  - name: install zsh
    command: dpkg -i /tmp/zsh_5.0.0-2ubuntu1_amd64.deb
  - name: set all users to use ZSH
    command: chsh -s /bin/zsh $item
    with_items:
      - skamithi
  - name: make /tmp use RAMdisk instead of hard disk
    lineinfile: dest=/etc/fstab backup=yes regexp="tmp\s+tmpfs" line="tmpfs /tmp tmpfs defaults 0 0"
  - name: make aptitude cache dir use RAM instead of HDD
    lineinfile: dest=/etc/fstab backup=yes regexp="archives\s+tmpfs" line="tmpfs /var/cache/apt/archives tmpfs defaults 0 0"
  - name: make user download dir use RAM instead of HDD
    lineinfile: dest=/etc/fstab backup=yes regexp="Downloads\s+tmpfs" line="tmpfs /home/skamithi/Downloads tmpfs defaults 0 0"

  - name: add vim to the update-alternatives editor list
    command: update-alternatives --install "/usr/bin/editor" "editor" "/usr/bin/vim" 5
  - name: set vim to the default editor
    command: update-alternatives --set "editor" "/usr/bin/vim"
  - name: install google chrome apt file
    copy: src=files/google-chrome.list dest=/etc/apt/sources.list.d/google-chrome.list
  - name: install chrome
    apt: pkg=google-chrome-stable force=yes
  - name: move tmp directory to RAM disk
    mount: name=/tmp src=tmpfs fstype=tmpfs state=mounted
  - name: move home directory download folder to RAM disk
    mount: name=/home/skamithi/Downloads src=tmpfs fstype=tmpfs state=mounted
  - name: move apt cache file to RAM disk
    mount: name=/var/cache/apt/archives src=tmpfs fstype=tmpfs state=mounted
  - name: disable bluetooth by default
    copy: src=files/bluetooth.conf dest=/etc/init/bluetooth.conf
  - name: temp workaround to resolve slow wifi connection on lenovo s431 on startup
    copy: src=files/network-interface.conf  dest=/etc/init/network-interface.conf
    when: is_s431
  - name: temp workaround to resolve slow wifi connection on resume
    copy: src=files/fix_slow_wifi_s431_resume  dest=/etc/pm/sleep.d/fix_slow_wifi_s431 mode=0755
    when: is_s431
  - name: add my user to virtualbox user group
    user: name=skamithi append=yes groups="vboxusers"
#  - include: compile-lldp.yml
#    vars:
#       tmp_dir: /tmp/lldp
  - name: replace printers.conf for CUPs. only works for home setup
    copy: src=files/printers.conf dest=/etc/cups/printers.conf owner=root group=lp mode=640 backup=yes
  - name : restart CUPS service
    service:  name=cups state=restarted

  - name: add my server to my hosts file
    lineinfile: dest=/etc/hosts regexp=^173.230.140.57 line="173.230.140.57    csf" backup=yes

  - name: copy chromedriver for rails development
    get_url: url=http://chromedriver.storage.googleapis.com/2.5/chromedriver_linux64.zip dest=/tmp/chrome.zip

  - name: install chromedriver in usr local dir
    command: unzip -qq -o /tmp/chrome.zip chdir=/usr/local/bin

  - name: set correct file permissions for chromedriver
    file: path=/usr/local/bin/chromedriver mode=0755
