#:set ft=ansible
- include: packages.yml
- include: tmpfs_dirs.yml
  tags: tmpfs

- name: include script to suspend VMS before sleep. prevents high cpu
  copy:
    src: suspend-vms
    dest: /etc/pm/sleep.d/suspend-vms
    mode: 0700

- name: make sure i can load my 64gb mmc card. Add quirk. Ref https://goo.gl/rwu4ci
  copy:
    content: "options sdhci debug_quirks2='0x10000'"
    dest: /etc/modprobe.d/sdhci.conf
  tags: fix_sdhci

- name: include script to reload wireless modules on resume/thaw
  copy:
    src: 100_reload_wireless
    dest: /etc/pm/sleep.d/100_reload_wireless
    mode: 0700
  tags: resume_wireless

- name: set sysctl to work with angular ng serve
  - sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present
