#:set ft=ansible
- include: packages.yml
- include: tmpfs_dirs.yml

- name: make sure i can load my 64gb mmc card. Add quirk. Ref https://goo.gl/rwu4ci
  copy:
    content: "options sdhci debug_quirks2='0x10000'"
    dest: /etc/modprobe.d/sdhci.conf

