- name: Cloning  oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "{{ ansible_user_dir}}/.oh-my-zsh"
  register: oh_my_zsh_cloning


- name: create .zshrc from oh-my-zsh templates
  copy:
    src: "{{ ansible_user_dir }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ ansible_user_dir }}/.zshrc"
  when: oh_my_zsh_cloning|changed
